### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by keroloussamy** [TheLuisAbarca/space-travelers-hub_react-redux#25]
The [Link](https://github.com/TheLuisAbarca/SpaceTravelersHub_React-Redux/projects/1) for the project.

Our team from 2 person
1- @TheLuisAbarca  => Missions
2- @keroloussamy   => Rockets

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @keroloussamy @TheLuisAbarca , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://media.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif)

Cheers and Happy coding!👏👏👏
